"project_id_env": "projectId"
"api_token_env": "personal-access-token"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

"files":[
  {
    "source": "/en/*",
    "translation": "/%two_letters_code%/%original_file_name%"
  },
]
