"project_id": "projectId"
"api_token": "personal-access-token"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

"files":[
  {
    "source": "/locale/en/folder1/[0-2].txt",
    "translation": "/locale/%two_letters_code%/folder1/%original_file_name%"
  },
]
